<h2> Importing necessary libraries

In [1]:
!pip install beautifulsoup4
!pip install lxml
import requests # library to handle requests
import pandas as pd # library for data analsysis
import numpy as np # library to handle data in a vectorized manner
import random # library for random number generation

!conda install -c conda-forge geopy --yes 
from geopy.geocoders import Nominatim # module to convert an address into latitude and longitude values

# libraries for displaying images
from IPython.display import Image 
from IPython.core.display import HTML 


from IPython.display import display_html
import pandas as pd
import numpy as np
    
# tranforming json file into a pandas dataframe library
from pandas.io.json import json_normalize

!conda install -c conda-forge folium=0.5.0 --yes
import folium # plotting library
from bs4 import BeautifulSoup
from sklearn.cluster import KMeans
import matplotlib.cm as cm
import matplotlib.colors as colors

print('Folium installed')
print('Libraries imported.')

Requirement already satisfied: beautifulsoup4 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (4.9.1)
Requirement already satisfied: soupsieve>1.2 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from beautifulsoup4) (2.0.1)
Requirement already satisfied: lxml in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (4.5.2)
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.8.4

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.8.4

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

Folium installed
Libraries imported.

In [2]:
import pandas as pd
import numpy as np
from pandas.io.html import read_html

page = "https://en.wikipedia.org/wiki/Districts_of_Madrid"

Madrid_table = pd.read_html(page, attrs={'class':'wikitable sortable'})

In [3]:
Madrid_df = pd.DataFrame(Madrid_table[0])
Madrid_df

,District Number,Name,District area[n 1] (Ha.),Population,Population density(Hab./Ha.),Location,Administrative wards
0,1.0,Centro,522.82,131928,252.34,NaN,Palacio (11)Embajadores (12)Cortes (13)Justici...
1,2.0,Arganzuela,646.22,151965,235.16,NaN,Imperial (21)Acacias (22)Chopera (23)Legazpi (...
2,3.0,Retiro,546.62,118516,216.82,NaN,Pacífico (31)Adelfas (32)Estrella (33)Ibiza (3...
3,4.0,Salamanca,539.24,143800,266.67,NaN,Recoletos (41)Goya (42)Fuente del Berro (43)Gu...
4,5.0,Chamartín,917.55,143424,156.31,NaN,El Viso (51)Prosperidad (52)Ciudad Jardín (53)...
5,6.0,Tetuán,537.47,153789,286.13,NaN,Bellas Vistas (61)Cuatro Caminos (62)Castillej...
6,7.0,Chamberí,467.92,137401,293.64,NaN,Gaztambide (71)Arapiles (72)Trafalgar (73)Alma...
7,8.0,Fuencarral-El Pardo,23783.84,238756,10.04,NaN,El Pardo (81)Fuentelarreina (82)Peñagrande (83...
8,9.0,Moncloa-Aravaca,4653.11,116903,25.12,NaN,Casa de Campo (91)Argüelles (92)Ciudad Univers...
9,10.0,Latina,2542.72,233808,91.95,NaN,Los Cármenes (101)Puerta del Ángel (102)Lucero...
10,11.0,Carabanchel,1404.83,243998,173.68,NaN,Comillas (111)Opañel (112)San Isidro (113)Vist...
11,12.0,Usera,777.77,134791,173.30,NaN,Orcasitas (121)Orcasur (122)San Fermín (123)Al...
12,13.0,Puente de Vallecas,1496.86,227595,152.05,NaN,Entrevías (131)San Diego (132)Palomeras Bajas ...
13,14.0,Moratalaz,610.32,94197,154.34,NaN,Pavones (141)Horcajo (142)Marroquina (143)Medi...
14,15.0,Ciudad Lineal,1142.57,212529,186.01,NaN,Ventas (151)Pueblo Nuevo (152)Quintana (153)Co...
15,16.0,Hortaleza,2741.98,180462,65.81,NaN,Palomas (161)Piovera (162)Canillas (163)Pinar ...
16,17.0,Villaverde,2018.76,142608,70.64,NaN,Villaverde Alto (171)San Cristóbal (172)Butarq...
17,18.0,Villa de Vallecas,5146.72,104421,19.86,NaN,Casco Histórico de Vallecas (181)Santa Eugenia...
18,19.0,Vicálvaro,3526.67,70051,19.86,NaN,Casco Histórico de Vicálvaro (191)Valdebernard...
19,20.0,San Blas-Canillejas,2229.24,154357,69.24,NaN,Simancas (201)Hellín (202)Amposta (203)Arcos (...
20,21.0,Barajas,4192.28,46876,11.18,NaN,Alameda de Osuna (211)Aeropuerto (212)Casco Hi...
21,NaN,TOTAL,60445.51,3182175,52.65,NaN,NaN

In [4]:
Madrid_df['City']= "Madrid"

In [5]:
Madrid_df['District Name']= "Distrito"

In [6]:
Madrid_df['Barrio'] = Madrid_df['District Name'] + ' ' + Madrid_df['Name'] + ', ' + Madrid_df['City']

In [7]:
Madrid_df

,District Number,Name,District area[n 1] (Ha.),Population,Population density(Hab./Ha.),Location,Administrative wards,City,District Name,Barrio
0,1.0,Centro,522.82,131928,252.34,NaN,Palacio (11)Embajadores (12)Cortes (13)Justici...,Madrid,Distrito,"Distrito Centro, Madrid"
1,2.0,Arganzuela,646.22,151965,235.16,NaN,Imperial (21)Acacias (22)Chopera (23)Legazpi (...,Madrid,Distrito,"Distrito Arganzuela, Madrid"
2,3.0,Retiro,546.62,118516,216.82,NaN,Pacífico (31)Adelfas (32)Estrella (33)Ibiza (3...,Madrid,Distrito,"Distrito Retiro, Madrid"
3,4.0,Salamanca,539.24,143800,266.67,NaN,Recoletos (41)Goya (42)Fuente del Berro (43)Gu...,Madrid,Distrito,"Distrito Salamanca, Madrid"
4,5.0,Chamartín,917.55,143424,156.31,NaN,El Viso (51)Prosperidad (52)Ciudad Jardín (53)...,Madrid,Distrito,"Distrito Chamartín, Madrid"
5,6.0,Tetuán,537.47,153789,286.13,NaN,Bellas Vistas (61)Cuatro Caminos (62)Castillej...,Madrid,Distrito,"Distrito Tetuán, Madrid"
6,7.0,Chamberí,467.92,137401,293.64,NaN,Gaztambide (71)Arapiles (72)Trafalgar (73)Alma...,Madrid,Distrito,"Distrito Chamberí, Madrid"
7,8.0,Fuencarral-El Pardo,23783.84,238756,10.04,NaN,El Pardo (81)Fuentelarreina (82)Peñagrande (83...,Madrid,Distrito,"Distrito Fuencarral-El Pardo, Madrid"
8,9.0,Moncloa-Aravaca,4653.11,116903,25.12,NaN,Casa de Campo (91)Argüelles (92)Ciudad Univers...,Madrid,Distrito,"Distrito Moncloa-Aravaca, Madrid"
9,10.0,Latina,2542.72,233808,91.95,NaN,Los Cármenes (101)Puerta del Ángel (102)Lucero...,Madrid,Distrito,"Distrito Latina, Madrid"
10,11.0,Carabanchel,1404.83,243998,173.68,NaN,Comillas (111)Opañel (112)San Isidro (113)Vist...,Madrid,Distrito,"Distrito Carabanchel, Madrid"
11,12.0,Usera,777.77,134791,173.30,NaN,Orcasitas (121)Orcasur (122)San Fermín (123)Al...,Madrid,Distrito,"Distrito Usera, Madrid"
12,13.0,Puente de Vallecas,1496.86,227595,152.05,NaN,Entrevías (131)San Diego (132)Palomeras Bajas ...,Madrid,Distrito,"Distrito Puente de Vallecas, Madrid"
13,14.0,Moratalaz,610.32,94197,154.34,NaN,Pavones (141)Horcajo (142)Marroquina (143)Medi...,Madrid,Distrito,"Distrito Moratalaz, Madrid"
14,15.0,Ciudad Lineal,1142.57,212529,186.01,NaN,Ventas (151)Pueblo Nuevo (152)Quintana (153)Co...,Madrid,Distrito,"Distrito Ciudad Lineal, Madrid"
15,16.0,Hortaleza,2741.98,180462,65.81,NaN,Palomas (161)Piovera (162)Canillas (163)Pinar ...,Madrid,Distrito,"Distrito Hortaleza, Madrid"
16,17.0,Villaverde,2018.76,142608,70.64,NaN,Villaverde Alto (171)San Cristóbal (172)Butarq...,Madrid,Distrito,"Distrito Villaverde, Madrid"
17,18.0,Villa de Vallecas,5146.72,104421,19.86,NaN,Casco Histórico de Vallecas (181)Santa Eugenia...,Madrid,Distrito,"Distrito Villa de Vallecas, Madrid"
18,19.0,Vicálvaro,3526.67,70051,19.86,NaN,Casco Histórico de Vicálvaro (191)Valdebernard...,Madrid,Distrito,"Distrito Vicálvaro, Madrid"
19,20.0,San Blas-Canillejas,2229.24,154357,69.24,NaN,Simancas (201)Hellín (202)Amposta (203)Arcos (...,Madrid,Distrito,"Distrito San Blas-Canillejas, Madrid"
20,21.0,Barajas,4192.28,46876,11.18,NaN,Alameda de Osuna (211)Aeropuerto (212)Casco Hi...,Madrid,Distrito,"Distrito Barajas, Madrid"
21,NaN,TOTAL,60445.51,3182175,52.65,NaN,NaN,Madrid,Distrito,"Distrito TOTAL, Madrid"

<h1> 3. Get the geographical coordinates

In [8]:
!pip install geopy

Requirement already satisfied: geopy in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (2.0.0)
Requirement already satisfied: geographiclib<2,>=1.49 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from geopy) (1.50)

In [9]:
address = 'Madrid, Madrid'
geolocator = Nominatim(user_agent="madrid_df")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Madrid, Spain are {}, {}.'.format(latitude,
longitude))

The geograpical coordinate of Madrid, Spain are 40.4167047, -3.7035825.

In [10]:
for address in (Madrid_df["Barrio"]):
          g = geolocator.geocode(address)
          print(g.address)
          print((g.latitude, g.longitude))

Calle Madrid, San Francisco - Ribera, Santiago, Distrito Centro, Córdoba, Andalucía, 14002, España
(37.8822217, -4.7756744)
Junta Municipal del Distrito de Arganzuela, 10, Paseo de la Chopera, Chopera, Arganzuela, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España
(40.392827, -3.6993131743246312)
Madrid, Bogotá, Bogotá Distrito Capital, 11001, Colombia
(4.561789, -74.1062406)
Junta Municipal de Distrito de Salamanca., 52, Calle de Velázquez, Recoletos, Salamanca, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España
(40.4273253, -3.683586539049173)
Distrito Chamartín, Avenida de Burgos, Castilla, Chamartín, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España
(40.476568150000006, -3.6752239743424773)
Distrito Tetuán, 9, Calle de los Algodonales, Berruguete, Tetuán, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28039, España
(40.4601708, -3.7004217)
Junta Municipal de Distrito de Moncloa-Aravaca., Intercambiador Moncloa Isla 2, Moncloa-Aravaca, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España
(40.43511875, -3.718717387233502)
Distrito Telefónica, Valverde, Fuencarral-El Pardo, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España
(40.514766800000004, -3.6636394865321593)
Junta Municipal de Distrito de Moncloa-Aravaca., Intercambiador Moncloa Isla 2, Moncloa-Aravaca, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España
(40.43511875, -3.718717387233502)
Plaza Distrito Latina, Latina, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España
(40.385127600000004, -3.764641679619886)
Junta Municipal de Distrito de Carabanchel., Calle de Monseñor Óscar Romero, Colonia de la Prensa, Carabanchel, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España
(40.380489999999995, -3.741458914602916)
Parque de Educación Vial-Distrito de Usera, 10, Orcasitas, Usera, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28041, España
(40.36523775, -3.711469322576959)
Junta Municipal de Distrito de Puente de Vallecas., 42, Avenida de la Albufera, Numancia, Puente de Vallecas, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28038, España
(40.3965208, -3.6664696537557173)
Junta Municipal de Distrito de Moratalaz., Calle de la Fuente Carrantona, Pavones, Moratalaz, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España
(40.39875635, -3.6367764093962274)
Junta Municipal de Distrito de Ciudad Lineal., 16, Calle de la Institución Libre de Enseñanza, Pueblo Nuevo, Ciudad Lineal, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28017, España
(40.4358511, -3.637071161618251)
Junta Municipal de Distrito de Hortaleza., Carretera de Canillas, Canillas, Hortaleza, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España
(40.462901349999996, -3.6569628463523145)
Junta Municipal de Distrito de Villaverde., Calle de Felipe Pingarrón, Villaverde Alto, Casco Histórico de Villaverde, Villaverde, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España
(40.348796699999994, -3.71120292313512)
Junta Municipal de Distrito de Villa de Vallecas, Paseo de Federico García Lorca, Casco Histórico de Vallecas, Villa de Vallecas, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España
(40.3788688, -3.621515607975871)
Punto Limpio del Distrito de Vicálvaro, Paseo del Polideportivo, Casco Histórico de Vicálvaro, Vicálvaro, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España
(40.406684150000004, -3.5985349108099234)
Junta Municipal de Distrito de San Blas-Canillejas., Calle de Normandía, Rosas, San Blas - Canillejas, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España
(40.434378249999995, -3.6096249999999994)
Junta Municipal de Distrito de Barajas., Calle Canal de Suez, Barajas, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España
(40.474829, -3.577778660404086)

AttributeError: 'NoneType' object has no attribute 'address'

<h3> After developing the loop for searching the coordinates, we can affirm there is some errors when identifying the points of the District. So, we manually created a .csv with the coordenates of the 21 district of Madrid

In [11]:
coord_Madrid = pd.read_excel('https://tinyurl.com/y6s2vxkp')
coord_Madrid.head()

         Name   Latitude  Longitude
0      Centro  40.415347  -3.707371
1  Arganzuela  40.402733  -3.695403
2      Retiro  40.408072  -3.676729
3   Salamanca  40.430000  -3.677780
4   Chamartín  40.453300  -3.677500

In [12]:
Madrid_df2 = pd.merge(Madrid_df, coord_Madrid, on ='Name')
Madrid_df2.head()

,District Number,Name,District area[n 1] (Ha.),Population,Population density(Hab./Ha.),Location,Administrative wards,City,District Name,Barrio,Latitude,Longitude
0,1.0,Centro,522.82,131928,252.34,NaN,Palacio (11)Embajadores (12)Cortes (13)Justici...,Madrid,Distrito,"Distrito Centro, Madrid",40.415347,-3.707371
1,2.0,Arganzuela,646.22,151965,235.16,NaN,Imperial (21)Acacias (22)Chopera (23)Legazpi (...,Madrid,Distrito,"Distrito Arganzuela, Madrid",40.402733,-3.695403
2,3.0,Retiro,546.62,118516,216.82,NaN,Pacífico (31)Adelfas (32)Estrella (33)Ibiza (3...,Madrid,Distrito,"Distrito Retiro, Madrid",40.408072,-3.676729
3,4.0,Salamanca,539.24,143800,266.67,NaN,Recoletos (41)Goya (42)Fuente del Berro (43)Gu...,Madrid,Distrito,"Distrito Salamanca, Madrid",40.430000,-3.677780
4,5.0,Chamartín,917.55,143424,156.31,NaN,El Viso (51)Prosperidad (52)Ciudad Jardín (53)...,Madrid,Distrito,"Distrito Chamartín, Madrid",40.453300,-3.677500

In [13]:
# save the DataFrame as CSV file
Madrid_df2.to_csv("Madrid_df_final.csv", index=False)

<h3> 4. Create a map of Madrid with neighborhoods

In [14]:
# create map of Madrid using latitude and longitude values
map_Mad = folium.Map(location=[latitude, longitude], zoom_start=11)

# add markers to map
for lat, lng, neighborhood in zip(Madrid_df2['Latitude'], Madrid_df2['Longitude'], Madrid_df2['Barrio']):
    label = '{}'.format(neighborhood)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_Mad)  
    
map_Mad

In [15]:
# save the map as HTML file
map_Mad.save('map_Mad.html')

<h3> 5. Use the Foursquare API to explore the neighborhoods

In [39]:
CLIENT_ID = '  ' # your FoursquareID
CLIENT_SECRET = '  ' # your Foursquare Secret
VERSION = '  '
LIMIT = 30
print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID:
CLIENT_SECRET:

<h4> Now, let's get the top 100 Movie Theaters that are within a radius of 2000 meters.

In [17]:
LIMIT = 100
radius = 2000
categoryId= "4bf58dd8d48988d17f941735" #This is the Foursquare Category Id for Movie Theaters
venues = []

for lat, long, neighborhood in zip(Madrid_df2['Latitude'], Madrid_df2['Longitude'], Madrid_df2['Name']):
    
    # create the API request URL
    url = "https://api.foursquare.com/v2/venues/explore?client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}&categoryId={}".format(
        CLIENT_ID,
        CLIENT_SECRET,
        VERSION,
        lat,
        long,
        radius, 
        LIMIT,
        categoryId)
    
    # make the GET request
    results = requests.get(url).json()["response"]['groups'][0]['items']
    
    # return only relevant information for each nearby venue
    for venue in results:
        venues.append((
            neighborhood,
            lat, 
            long, 
            venue['venue']['name'], 
            venue['venue']['location']['lat'], 
            venue['venue']['location']['lng'],  
            venue['venue']['categories'][0]['name']))

In [18]:
# convert the venues list into a new DataFrame
venues_df = pd.DataFrame(venues)

# define the column names
venues_df.columns = ['Neighborhood', 'Latitude', 'Longitude', 'VenueName', 'VenueLatitude', 'VenueLongitude', 'VenueCategory']

print(venues_df.shape)
venues_df

(134, 7)

,Neighborhood,Latitude,Longitude,VenueName,VenueLatitude,VenueLongitude,VenueCategory
0,Centro,40.415347,-3.707371,Yelmo Cines Ideal,40.413775,-3.703745,Multiplex
1,Centro,40.415347,-3.707371,Cines Callao - Callao City Lights,40.420235,-3.706089,Movie Theater
2,Centro,40.415347,-3.707371,Cine Doré,40.411833,-3.699267,Movie Theater
3,Centro,40.415347,-3.707371,Cines Golem,40.424703,-3.713700,Movie Theater
4,Centro,40.415347,-3.707371,Renoir Plaza España,40.424343,-3.713386,Movie Theater
...,...,...,...,...,...,...,...
129,Vicálvaro,40.404200,-3.608060,Centro Comercial Manoteras,40.398313,-3.605202,Multiplex
130,Vicálvaro,40.404200,-3.608060,Cine 3D,40.391545,-3.610527,Movie Theater
131,Vicálvaro,40.404200,-3.608060,Cinesa Las Rosas 3D,40.418567,-3.620932,Multiplex
132,San Blas-Canillejas,40.426001,-3.612764,Cinesa Las Rosas 3D,40.418567,-3.620932,Multiplex
133,San Blas-Canillejas,40.426001,-3.612764,Sala de proyecciones Deluxe,40.432081,-3.632247,Indie Movie Theater

In [19]:
venues_df.groupby(["Neighborhood"]).count()

,Latitude,Longitude,VenueName,VenueLatitude,VenueLongitude,VenueCategory
Neighborhood,,,,,,
Arganzuela,11,11,11,11,11,11
Carabanchel,2,2,2,2,2,2
Centro,27,27,27,27,27,27
Chamartín,4,4,4,4,4,4
Chamberí,24,24,24,24,24,24
Ciudad Lineal,4,4,4,4,4,4
Fuencarral-El Pardo,5,5,5,5,5,5
Hortaleza,3,3,3,3,3,3
Latina,1,1,1,1,1,1
Moncloa-Aravaca,23,23,23,23,23,23
Moratalaz,1,1,1,1,1,1
Puente de Vallecas,3,3,3,3,3,3
Retiro,6,6,6,6,6,6
Salamanca,6,6,6,6,6,6
San Blas-Canillejas,2,2,2,2,2,2
Tetuán,2,2,2,2,2,2
Usera,6,6,6,6,6,6
Vicálvaro,3,3,3,3,3,3
Villa de Vallecas,1,1,1,1,1,1

<h3> 6. Analyze Each Neighborhood

In [20]:
# one hot encoding
Madrid_onehot = pd.get_dummies(venues_df[['VenueCategory']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
Madrid_onehot['Neighborhoods'] = venues_df['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [Madrid_onehot.columns[-1]] + list(Madrid_onehot.columns[:-1])
Madrid_onehot = Madrid_onehot[fixed_columns]

print(Madrid_onehot.shape)
Madrid_onehot.head()

(134, 6)

,Neighborhoods,Indie Movie Theater,Movie Theater,Multiplex,Performing Arts Venue,Theater
0,Centro,0,0,1,0,0
1,Centro,0,1,0,0,0
2,Centro,0,1,0,0,0
3,Centro,0,1,0,0,0
4,Centro,0,1,0,0,0

<h5> Next, let's group rows by neighborhood and by taking the mean of the frequency of occurrence of each category

In [21]:
Madrid_grouped = Madrid_onehot.groupby(["Neighborhoods"]).mean().reset_index()

print(Madrid_grouped.shape)
Madrid_grouped

(19, 6)

,Neighborhoods,Indie Movie Theater,Movie Theater,Multiplex,Performing Arts Venue,Theater
0,Arganzuela,0.363636,0.363636,0.181818,0.000000,0.090909
1,Carabanchel,0.500000,0.500000,0.000000,0.000000,0.000000
2,Centro,0.185185,0.592593,0.148148,0.037037,0.037037
3,Chamartín,0.000000,0.750000,0.250000,0.000000,0.000000
4,Chamberí,0.125000,0.708333,0.125000,0.041667,0.000000
5,Ciudad Lineal,0.000000,0.750000,0.250000,0.000000,0.000000
6,Fuencarral-El Pardo,0.200000,0.600000,0.200000,0.000000,0.000000
7,Hortaleza,0.333333,0.333333,0.333333,0.000000,0.000000
8,Latina,0.000000,1.000000,0.000000,0.000000,0.000000
9,Moncloa-Aravaca,0.086957,0.695652,0.173913,0.043478,0.000000
10,Moratalaz,0.000000,1.000000,0.000000,0.000000,0.000000
11,Puente de Vallecas,0.000000,0.666667,0.333333,0.000000,0.000000
12,Retiro,0.000000,0.833333,0.166667,0.000000,0.000000
13,Salamanca,0.000000,0.833333,0.166667,0.000000,0.000000
14,San Blas-Canillejas,0.500000,0.000000,0.500000,0.000000,0.000000
15,Tetuán,0.000000,1.000000,0.000000,0.000000,0.000000
16,Usera,0.666667,0.333333,0.000000,0.000000,0.000000
17,Vicálvaro,0.000000,0.333333,0.666667,0.000000,0.000000
18,Villa de Vallecas,0.000000,1.000000,0.000000,0.000000,0.000000

<h4> Create a new DataFrame for Movie Theaters data only

In [22]:
Madrid_theaters = Madrid_grouped[["Neighborhoods","Movie Theater"]]
Madrid_theaters

          Neighborhoods  Movie Theater
0            Arganzuela       0.363636
1           Carabanchel       0.500000
2                Centro       0.592593
3             Chamartín       0.750000
4              Chamberí       0.708333
5         Ciudad Lineal       0.750000
6   Fuencarral-El Pardo       0.600000
7             Hortaleza       0.333333
8                Latina       1.000000
9       Moncloa-Aravaca       0.695652
10            Moratalaz       1.000000
11   Puente de Vallecas       0.666667
12               Retiro       0.833333
13            Salamanca       0.833333
14  San Blas-Canillejas       0.000000
15               Tetuán       1.000000
16                Usera       0.333333
17            Vicálvaro       0.333333
18    Villa de Vallecas       1.000000

<h4> 7. Cluster Neighborhoods

<h5> Run k-means to cluster the neighborhoods in Madrid into 4 clusters.

In [23]:
# set number of clusters
kclusters = 4

mad_clustering = Madrid_theaters.drop(["Neighborhoods"], 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(mad_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10]

array([1, 1, 2, 2, 2, 2, 2, 1, 0, 2], dtype=int32)

In [24]:
# create a new dataframe that includes the cluster 
mad_merged = Madrid_theaters.copy()

# add clustering labels
mad_merged["Cluster Labels"] = kmeans.labels_

In [30]:
mad_merged.rename(columns={"Neighborhoods": "Name"}, inplace=True)
mad_merged.head()

          Name  Movie Theater  Cluster Labels
0   Arganzuela       0.363636               1
1  Carabanchel       0.500000               1
2       Centro       0.592593               2
3    Chamartín       0.750000               2
4     Chamberí       0.708333               2

In [31]:
mad_merged = mad_merged.join(Madrid_df2.set_index("Name"), on="Name")
print(mad_merged.shape)

(19, 14)

In [32]:
mad_merged.head()

,Name,Movie Theater,Cluster Labels,District Number,District area[n 1] (Ha.),Population,Population density(Hab./Ha.),Location,Administrative wards,City,District Name,Barrio,Latitude,Longitude
0,Arganzuela,0.363636,1,2.0,646.22,151965,235.16,NaN,Imperial (21)Acacias (22)Chopera (23)Legazpi (...,Madrid,Distrito,"Distrito Arganzuela, Madrid",40.402733,-3.695403
1,Carabanchel,0.500000,1,11.0,1404.83,243998,173.68,NaN,Comillas (111)Opañel (112)San Isidro (113)Vist...,Madrid,Distrito,"Distrito Carabanchel, Madrid",40.383700,-3.728000
2,Centro,0.592593,2,1.0,522.82,131928,252.34,NaN,Palacio (11)Embajadores (12)Cortes (13)Justici...,Madrid,Distrito,"Distrito Centro, Madrid",40.415347,-3.707371
3,Chamartín,0.750000,2,5.0,917.55,143424,156.31,NaN,El Viso (51)Prosperidad (52)Ciudad Jardín (53)...,Madrid,Distrito,"Distrito Chamartín, Madrid",40.453300,-3.677500
4,Chamberí,0.708333,2,7.0,467.92,137401,293.64,NaN,Gaztambide (71)Arapiles (72)Trafalgar (73)Alma...,Madrid,Distrito,"Distrito Chamberí, Madrid",40.432800,-3.697200

In [33]:
# sort the results by Cluster Labels
print(mad_merged.shape)
mad_merged.sort_values(["Cluster Labels"], inplace=True)
mad_merged

(19, 14)

,Name,Movie Theater,Cluster Labels,District Number,District area[n 1] (Ha.),Population,Population density(Hab./Ha.),Location,Administrative wards,City,District Name,Barrio,Latitude,Longitude
18,Villa de Vallecas,1.000000,0,18.0,5146.72,104421,19.86,NaN,Casco Histórico de Vallecas (181)Santa Eugenia...,Madrid,Distrito,"Distrito Villa de Vallecas, Madrid",40.380000,-3.620000
15,Tetuán,1.000000,0,6.0,537.47,153789,286.13,NaN,Bellas Vistas (61)Cuatro Caminos (62)Castillej...,Madrid,Distrito,"Distrito Tetuán, Madrid",40.460560,-3.700000
10,Moratalaz,1.000000,0,14.0,610.32,94197,154.34,NaN,Pavones (141)Horcajo (142)Marroquina (143)Medi...,Madrid,Distrito,"Distrito Moratalaz, Madrid",40.409900,-3.644400
8,Latina,1.000000,0,10.0,2542.72,233808,91.95,NaN,Los Cármenes (101)Puerta del Ángel (102)Lucero...,Madrid,Distrito,"Distrito Latina, Madrid",40.402461,-3.741294
16,Usera,0.333333,1,12.0,777.77,134791,173.30,NaN,Orcasitas (121)Orcasur (122)San Fermín (123)Al...,Madrid,Distrito,"Distrito Usera, Madrid",40.381300,-3.706900
17,Vicálvaro,0.333333,1,19.0,3526.67,70051,19.86,NaN,Casco Histórico de Vicálvaro (191)Valdebernard...,Madrid,Distrito,"Distrito Vicálvaro, Madrid",40.404200,-3.608060
7,Hortaleza,0.333333,1,16.0,2741.98,180462,65.81,NaN,Palomas (161)Piovera (162)Canillas (163)Pinar ...,Madrid,Distrito,"Distrito Hortaleza, Madrid",40.469457,-3.640482
0,Arganzuela,0.363636,1,2.0,646.22,151965,235.16,NaN,Imperial (21)Acacias (22)Chopera (23)Legazpi (...,Madrid,Distrito,"Distrito Arganzuela, Madrid",40.402733,-3.695403
1,Carabanchel,0.500000,1,11.0,1404.83,243998,173.68,NaN,Comillas (111)Opañel (112)San Isidro (113)Vist...,Madrid,Distrito,"Distrito Carabanchel, Madrid",40.383700,-3.728000
5,Ciudad Lineal,0.750000,2,15.0,1142.57,212529,186.01,NaN,Ventas (151)Pueblo Nuevo (152)Quintana (153)Co...,Madrid,Distrito,"Distrito Ciudad Lineal, Madrid",40.450000,-3.650000
4,Chamberí,0.708333,2,7.0,467.92,137401,293.64,NaN,Gaztambide (71)Arapiles (72)Trafalgar (73)Alma...,Madrid,Distrito,"Distrito Chamberí, Madrid",40.432800,-3.697200
3,Chamartín,0.750000,2,5.0,917.55,143424,156.31,NaN,El Viso (51)Prosperidad (52)Ciudad Jardín (53)...,Madrid,Distrito,"Distrito Chamartín, Madrid",40.453300,-3.677500
11,Puente de Vallecas,0.666667,2,13.0,1496.86,227595,152.05,NaN,Entrevías (131)San Diego (132)Palomeras Bajas ...,Madrid,Distrito,"Distrito Puente de Vallecas, Madrid",40.398204,-3.669059
12,Retiro,0.833333,2,3.0,546.62,118516,216.82,NaN,Pacífico (31)Adelfas (32)Estrella (33)Ibiza (3...,Madrid,Distrito,"Distrito Retiro, Madrid",40.408072,-3.676729
13,Salamanca,0.833333,2,4.0,539.24,143800,266.67,NaN,Recoletos (41)Goya (42)Fuente del Berro (43)Gu...,Madrid,Distrito,"Distrito Salamanca, Madrid",40.430000,-3.677780
2,Centro,0.592593,2,1.0,522.82,131928,252.34,NaN,Palacio (11)Embajadores (12)Cortes (13)Justici...,Madrid,Distrito,"Distrito Centro, Madrid",40.415347,-3.707371
6,Fuencarral-El Pardo,0.600000,2,8.0,23783.84,238756,10.04,NaN,El Pardo (81)Fuentelarreina (82)Peñagrande (83...,Madrid,Distrito,"Distrito Fuencarral-El Pardo, Madrid",40.478600,-3.709700
9,Moncloa-Aravaca,0.695652,2,9.0,4653.11,116903,25.12,NaN,Casa de Campo (91)Argüelles (92)Ciudad Univers...,Madrid,Distrito,"Distrito Moncloa-Aravaca, Madrid",40.435151,-3.718765
14,San Blas-Canillejas,0.000000,3,20.0,2229.24,154357,69.24,NaN,Simancas (201)Hellín (202)Amposta (203)Arcos (...,Madrid,Distrito,"Distrito San Blas-Canillejas, Madrid",40.426001,-3.612764

<h5> Finally, let's visualize the resulting clusters

In [34]:
madmap_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i+x+(i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(mad_merged['Latitude'], mad_merged['Longitude'], mad_merged['Name'], mad_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' - Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.8).add_to(madmap_clusters)
       
madmap_clusters

<h3> 8. Examine Clusters

<h3> Cluster 0

In [35]:
mad_merged.loc[mad_merged['Cluster Labels'] == 0]

,Name,Movie Theater,Cluster Labels,District Number,District area[n 1] (Ha.),Population,Population density(Hab./Ha.),Location,Administrative wards,City,District Name,Barrio,Latitude,Longitude
18,Villa de Vallecas,1.0,0,18.0,5146.72,104421,19.86,NaN,Casco Histórico de Vallecas (181)Santa Eugenia...,Madrid,Distrito,"Distrito Villa de Vallecas, Madrid",40.380000,-3.620000
15,Tetuán,1.0,0,6.0,537.47,153789,286.13,NaN,Bellas Vistas (61)Cuatro Caminos (62)Castillej...,Madrid,Distrito,"Distrito Tetuán, Madrid",40.460560,-3.700000
10,Moratalaz,1.0,0,14.0,610.32,94197,154.34,NaN,Pavones (141)Horcajo (142)Marroquina (143)Medi...,Madrid,Distrito,"Distrito Moratalaz, Madrid",40.409900,-3.644400
8,Latina,1.0,0,10.0,2542.72,233808,91.95,NaN,Los Cármenes (101)Puerta del Ángel (102)Lucero...,Madrid,Distrito,"Distrito Latina, Madrid",40.402461,-3.741294

<h3> Cluster 1

In [36]:
mad_merged.loc[mad_merged['Cluster Labels'] == 1]

,Name,Movie Theater,Cluster Labels,District Number,District area[n 1] (Ha.),Population,Population density(Hab./Ha.),Location,Administrative wards,City,District Name,Barrio,Latitude,Longitude
16,Usera,0.333333,1,12.0,777.77,134791,173.30,NaN,Orcasitas (121)Orcasur (122)San Fermín (123)Al...,Madrid,Distrito,"Distrito Usera, Madrid",40.381300,-3.706900
17,Vicálvaro,0.333333,1,19.0,3526.67,70051,19.86,NaN,Casco Histórico de Vicálvaro (191)Valdebernard...,Madrid,Distrito,"Distrito Vicálvaro, Madrid",40.404200,-3.608060
7,Hortaleza,0.333333,1,16.0,2741.98,180462,65.81,NaN,Palomas (161)Piovera (162)Canillas (163)Pinar ...,Madrid,Distrito,"Distrito Hortaleza, Madrid",40.469457,-3.640482
0,Arganzuela,0.363636,1,2.0,646.22,151965,235.16,NaN,Imperial (21)Acacias (22)Chopera (23)Legazpi (...,Madrid,Distrito,"Distrito Arganzuela, Madrid",40.402733,-3.695403
1,Carabanchel,0.500000,1,11.0,1404.83,243998,173.68,NaN,Comillas (111)Opañel (112)San Isidro (113)Vist...,Madrid,Distrito,"Distrito Carabanchel, Madrid",40.383700,-3.728000

<h3> Cluster 2

In [37]:
mad_merged.loc[mad_merged['Cluster Labels'] == 2]

,Name,Movie Theater,Cluster Labels,District Number,District area[n 1] (Ha.),Population,Population density(Hab./Ha.),Location,Administrative wards,City,District Name,Barrio,Latitude,Longitude
5,Ciudad Lineal,0.750000,2,15.0,1142.57,212529,186.01,NaN,Ventas (151)Pueblo Nuevo (152)Quintana (153)Co...,Madrid,Distrito,"Distrito Ciudad Lineal, Madrid",40.450000,-3.650000
4,Chamberí,0.708333,2,7.0,467.92,137401,293.64,NaN,Gaztambide (71)Arapiles (72)Trafalgar (73)Alma...,Madrid,Distrito,"Distrito Chamberí, Madrid",40.432800,-3.697200
3,Chamartín,0.750000,2,5.0,917.55,143424,156.31,NaN,El Viso (51)Prosperidad (52)Ciudad Jardín (53)...,Madrid,Distrito,"Distrito Chamartín, Madrid",40.453300,-3.677500
11,Puente de Vallecas,0.666667,2,13.0,1496.86,227595,152.05,NaN,Entrevías (131)San Diego (132)Palomeras Bajas ...,Madrid,Distrito,"Distrito Puente de Vallecas, Madrid",40.398204,-3.669059
12,Retiro,0.833333,2,3.0,546.62,118516,216.82,NaN,Pacífico (31)Adelfas (32)Estrella (33)Ibiza (3...,Madrid,Distrito,"Distrito Retiro, Madrid",40.408072,-3.676729
13,Salamanca,0.833333,2,4.0,539.24,143800,266.67,NaN,Recoletos (41)Goya (42)Fuente del Berro (43)Gu...,Madrid,Distrito,"Distrito Salamanca, Madrid",40.430000,-3.677780
2,Centro,0.592593,2,1.0,522.82,131928,252.34,NaN,Palacio (11)Embajadores (12)Cortes (13)Justici...,Madrid,Distrito,"Distrito Centro, Madrid",40.415347,-3.707371
6,Fuencarral-El Pardo,0.600000,2,8.0,23783.84,238756,10.04,NaN,El Pardo (81)Fuentelarreina (82)Peñagrande (83...,Madrid,Distrito,"Distrito Fuencarral-El Pardo, Madrid",40.478600,-3.709700
9,Moncloa-Aravaca,0.695652,2,9.0,4653.11,116903,25.12,NaN,Casa de Campo (91)Argüelles (92)Ciudad Univers...,Madrid,Distrito,"Distrito Moncloa-Aravaca, Madrid",40.435151,-3.718765

<h3> Cluster 3

In [38]:
mad_merged.loc[mad_merged['Cluster Labels'] == 3]

,Name,Movie Theater,Cluster Labels,District Number,District area[n 1] (Ha.),Population,Population density(Hab./Ha.),Location,Administrative wards,City,District Name,Barrio,Latitude,Longitude
14,San Blas-Canillejas,0.0,3,20.0,2229.24,154357,69.24,NaN,Simancas (201)Hellín (202)Amposta (203)Arcos (...,Madrid,Distrito,"Distrito San Blas-Canillejas, Madrid",40.426001,-3.612764